/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perecords;
import javax.swing.*;
import java.awt.Color;
import javax.swing.event.ChangeListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
/**
 *
 * @author BPRAdmin
 */
public class contacts extends javax.swing.JFrame {
    boolean sess=false;int uid;
    prerecordsmgr records=new prerecordsmgr();
   
    /**
     * Creates new form PeRecords
     */
    public contacts() {
        //JOptionPane.showMessageDialog(null,"Sessions: "+records.session);
        initComponents();
        records.getContacts(tblCont);
    }
     public void cleanContactForm(){//cleaning the form after insert made
     txtFldUname.setText("");
     txtFldNickName.setText("");
     txtFldPhone.setText("");
     txtFldEmail.setText("");
     txtFldLocation.setText("");
     radMale.setSelected(true);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String sex="male";
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegCont = new javax.swing.JButton();
        lblSex = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtFldLocation = new javax.swing.JTextField();
        txtFldEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtFldPhone = new javax.swing.JTextField();
        txtFldNickName = new javax.swing.JTextField();
        lblNickName = new javax.swing.JLabel();
        txtFldUname = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        btnUpdCont = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSearchCont = new javax.swing.JButton();
        btnDelCont = new javax.swing.JButton();
        txtFldSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCont = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        btnMenuContact = new javax.swing.JButton();
        btnMenuPlan = new javax.swing.JButton();
        btnMenuGoals = new javax.swing.JButton();
        btnMenuProjects = new javax.swing.JButton();
        btnMneuTrips = new javax.swing.JButton();
        btnMenuMedias = new javax.swing.JButton();
        btnMenuLifeStyle = new javax.swing.JButton();
        btnMenuLogout = new javax.swing.JButton();
        btnMenuSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONAL RECORDS MANAGEMENT SYSTEM");
        setBackground(new java.awt.Color(0, 255, 255));
        setForeground(new java.awt.Color(204, 255, 0));
        setLocation(new java.awt.Point(10, 50));
        setPreferredSize(new java.awt.Dimension(1338, 617));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jTextField1.setText("                                                                 MANAGE CONTACTS");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRegCont.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnRegCont.setText("Register");
        btnRegCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegContActionPerformed(evt);
            }
        });

        lblSex.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblSex.setText("Sex");

        lblLocation.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        txtFldLocation.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        txtFldEmail.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblEmail.setText("E-mail");

        lblPhone.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblPhone.setText("Phone");

        txtFldPhone.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        txtFldNickName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        lblNickName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblNickName.setText("Nick Name");

        txtFldUname.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        lblName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblName.setText("Name");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("                      Register New Contact");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        buttonGroup1.add(radMale);
        radMale.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        radMale.setSelected(true);
        radMale.setText("Male");
        radMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radFemale);
        radFemale.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        radFemale.setText("Female");
        radFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFemaleActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField8.setText("    Register Unlimited Number of Contacts");

        btnUpdCont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdCont.setText("Update");
        btnUpdCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdContActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFldNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(radMale, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(radFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFldLocation)
                                        .addGap(4, 4, 4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRegCont, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdCont, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFldUname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmail, lblLocation, lblName, lblNickName, lblPhone, lblSex});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radFemale, radMale});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRegCont, btnUpdCont});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldUname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radMale)
                    .addComponent(radFemale))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegCont, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEmail, lblLocation, lblName, lblNickName, lblPhone, lblSex, txtFldEmail, txtFldNickName, txtFldPhone, txtFldUname});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRegCont, btnUpdCont});

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnSearchCont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchCont.setText("SEARCH");
        btnSearchCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSearchCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchContActionPerformed(evt);
            }
        });

        btnDelCont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelCont.setText("Delete");
        btnDelCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelContActionPerformed(evt);
            }
        });

        txtFldSearch.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelCont, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelCont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "NICKNAME", "PHONE", "E-MAIL", "LOCATION", "SEX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCont);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField5.setText("        MENUS");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField5.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuContact.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuContact.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuContact.setText("Contact");
        btnMenuContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContactActionPerformed(evt);
            }
        });

        btnMenuPlan.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPlan.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPlan.setText("Plan");
        btnMenuPlan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuPlan.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPlanActionPerformed(evt);
            }
        });

        btnMenuGoals.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuGoals.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuGoals.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuGoals.setText("Goals");
        btnMenuGoals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuGoals.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuProjects.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuProjects.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuProjects.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuProjects.setText("Projects");
        btnMenuProjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuProjects.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProjectsActionPerformed(evt);
            }
        });

        btnMneuTrips.setBackground(new java.awt.Color(0, 0, 0));
        btnMneuTrips.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMneuTrips.setForeground(new java.awt.Color(255, 255, 255));
        btnMneuTrips.setText("Trips");
        btnMneuTrips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMneuTrips.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMneuTrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMneuTripsActionPerformed(evt);
            }
        });

        btnMenuMedias.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuMedias.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuMedias.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuMedias.setText("Medias");
        btnMenuMedias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuMedias.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMediasActionPerformed(evt);
            }
        });

        btnMenuLifeStyle.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLifeStyle.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLifeStyle.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLifeStyle.setText("Life Style");
        btnMenuLifeStyle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLifeStyle.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuLifeStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLifeStyleActionPerformed(evt);
            }
        });

        btnMenuLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLogout.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLogout.setText("Logout");
        btnMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLogout.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuSetting.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuSetting.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSetting.setText("Setting");
        btnMenuSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuSetting.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMenuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuProjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnMenuMedias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMneuTrips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMenuContact, btnMenuGoals, btnMenuLifeStyle, btnMenuMedias, btnMenuPlan, btnMneuTrips});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMenuContact)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMenuGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMneuTrips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMedias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMenuContact, btnMenuGoals, btnMenuLifeStyle, btnMenuMedias, btnMenuPlan, btnMenuProjects, btnMneuTrips});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formAncestorResized

    private void btnMenuMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMediasActionPerformed
        this.setVisible(false);
        new medias().setVisible(true);
    }//GEN-LAST:event_btnMenuMediasActionPerformed

    private void btnMenuContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContactActionPerformed
       this.setVisible(true);
    }//GEN-LAST:event_btnMenuContactActionPerformed

    private void btnMenuPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPlanActionPerformed
        this.setVisible(false);
        new plan().setVisible(true);
    }//GEN-LAST:event_btnMenuPlanActionPerformed

    private void btnMenuProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProjectsActionPerformed
        this.setVisible(false);
        new projects().setVisible(true);
    }//GEN-LAST:event_btnMenuProjectsActionPerformed

    private void btnMneuTripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMneuTripsActionPerformed
        this.setVisible(false);
        new trips().setVisible(true);
    }//GEN-LAST:event_btnMneuTripsActionPerformed

    private void btnMenuLifeStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLifeStyleActionPerformed
       this.setVisible(false);
        new lifestyle().setVisible(true);
    }//GEN-LAST:event_btnMenuLifeStyleActionPerformed

    private void btnMenuSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSettingActionPerformed
        this.setVisible(false);
        new setting().setVisible(true);
    }//GEN-LAST:event_btnMenuSettingActionPerformed

    private void btnRegContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegContActionPerformed
        records.addContacts(txtFldUname.getText(),txtFldNickName.getText(),txtFldPhone.getText(),txtFldEmail.getText(),txtFldLocation.getText(),
                sex);
        cleanContactForm();
        records.getContacts(tblCont);
    }//GEN-LAST:event_btnRegContActionPerformed

    private void radMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaleActionPerformed
        sex="male";
    }//GEN-LAST:event_radMaleActionPerformed

    private void radFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFemaleActionPerformed
       sex="female";
    }//GEN-LAST:event_radFemaleActionPerformed

    private void tblContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContMouseClicked
      try{
        TableModel tmodel=tblCont.getModel();
        int i=tblCont.getSelectedRow();
        uid=Integer.parseInt(tmodel.getValueAt(i,0).toString());
        txtFldUname.setText(tmodel.getValueAt(i,1).toString());
        txtFldNickName.setText(tmodel.getValueAt(i,2).toString());
        txtFldPhone.setText(tmodel.getValueAt(i,3).toString());
        txtFldEmail.setText(tmodel.getValueAt(i,4).toString());
        txtFldLocation.setText(tmodel.getValueAt(i,5).toString());
    if(tmodel.getValueAt(i,6).toString().equals("male")){
            radMale.setSelected(true);
            radFemale.setSelected(false); 
        }else{
            radMale.setSelected(false);radFemale.setSelected(true); 
        }
     }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_tblContMouseClicked

    private void btnUpdContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdContActionPerformed
      try{
        if(records.updateContacts(uid,txtFldUname.getText(),txtFldNickName.getText(),txtFldPhone.getText(),txtFldEmail.getText(),txtFldLocation.getText(),
                    sex)) records.getContacts(tblCont);
         cleanContactForm();
         records.getContacts(tblCont);
          }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnUpdContActionPerformed

    private void btnDelContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelContActionPerformed
        try{
        records.deleteContacts(uid);
         cleanContactForm();
         records.getContacts(tblCont);
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnDelContActionPerformed

    private void btnSearchContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchContActionPerformed
      try{
          if(txtFldSearch.getText().equals("*")){
            records.getContacts(tblCont);
        }else{
        records.searchContacts(tblCont,txtFldSearch.getText());
        }
     }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnSearchContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelCont;
    private javax.swing.JButton btnMenuContact;
    private javax.swing.JButton btnMenuGoals;
    private javax.swing.JButton btnMenuLifeStyle;
    private javax.swing.JButton btnMenuLogout;
    private javax.swing.JButton btnMenuMedias;
    private javax.swing.JButton btnMenuPlan;
    private javax.swing.JButton btnMenuProjects;
    private javax.swing.JButton btnMenuSetting;
    private javax.swing.JButton btnMneuTrips;
    private javax.swing.JButton btnRegCont;
    private javax.swing.JButton btnSearchCont;
    private javax.swing.JButton btnUpdCont;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNickName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSex;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTable tblCont;
    private javax.swing.JTextField txtFldEmail;
    private javax.swing.JTextField txtFldLocation;
    private javax.swing.JTextField txtFldNickName;
    private javax.swing.JTextField txtFldPhone;
    private javax.swing.JTextField txtFldSearch;
    private javax.swing.JTextField txtFldUname;
    // End of variables declaration//GEN-END:variables
}
