/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perecords;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author BPRAdmin
 */
public class lifestyle extends javax.swing.JFrame{
prerecordsmgr records=new prerecordsmgr();
    /**
     * Creates new form lifestyle
     */
    public lifestyle() {
        initComponents();
       // records.getLifeStyle(lstLfsFuture);
        records.futureLifeStyle(lstLfsFuture);
        records.intimeLifeStyle(lstLfsIn);
        records.expiredLifeStyle(lstLfsExp);
    }
    public void clearLfsForm(){
     txtFldLfsTitle.setText("");
     txtFldLfsDescr.setText("");
     comboLfsType.setSelectedItem(0);
     txtFldLfsStrtDate.setText("");
     txtFldLfsStpDate.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFldLfsDescr = new javax.swing.JTextArea();
        lblDescr = new javax.swing.JLabel();
        comboLfsType = new javax.swing.JComboBox();
        lblType = new javax.swing.JLabel();
        txtFldLfsTitle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblStart = new javax.swing.JLabel();
        lblStop = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFldLfsStpDate = new javax.swing.JTextField();
        txtFldLfsStrtDate = new javax.swing.JTextField();
        btnRegLfs = new javax.swing.JButton();
        btnUpdLfs = new javax.swing.JButton();
        btnClearLfs = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstLfsFuture = new javax.swing.JList();
        lblMsgLfsFt = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnDelLfsFt = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstLfsIn = new javax.swing.JList();
        lblMsgLfsIn = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnDelLfsIn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        lstLfsExp = new javax.swing.JList();
        lblMsgLfsExp = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnDelLfsExp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnViewLfsClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFldLfsView = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTrgtFocussed = new javax.swing.JList();
        txtFldTrgtSearchFocussed = new javax.swing.JTextField();
        btnTrgtSearchFocussed = new javax.swing.JButton();
        lblMsgTrgtFocussed = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtFldTrgtSearchExp = new javax.swing.JTextField();
        btnTrgtSearchExp = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstTrgtExp = new javax.swing.JList();
        lblMsgTrgtExp = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFldTrgtDeadline = new javax.swing.JTextField();
        txtFldTrgtName = new javax.swing.JTextField();
        lblTrgtName = new javax.swing.JLabel();
        btnTrgtView = new javax.swing.JButton();
        btnTrgtEdit = new javax.swing.JButton();
        btnTrgtDel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        btnMenuContact = new javax.swing.JButton();
        btnMenuPlan = new javax.swing.JButton();
        btnMenuGoals = new javax.swing.JButton();
        btnMenuProjects = new javax.swing.JButton();
        btnMneuTrips = new javax.swing.JButton();
        btnMenuMedias = new javax.swing.JButton();
        btnMenuLifeStyle = new javax.swing.JButton();
        btnMenuLogout = new javax.swing.JButton();
        btnMenuSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONAL RECORDS MANAGEMENT SYSTEM");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jTextField1.setText("                                                                     LIFESTYLES MANAGEMENT");
        jTextField1.setPreferredSize(new java.awt.Dimension(677, 36));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtFldLfsDescr.setColumns(20);
        txtFldLfsDescr.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtFldLfsDescr.setRows(5);
        jScrollPane2.setViewportView(txtFldLfsDescr);

        lblDescr.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblDescr.setText("Description");

        comboLfsType.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        comboLfsType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Conditions", "Daily Life", "Society", "Love" }));

        lblType.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblType.setText("Type");

        txtFldLfsTitle.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel11.setText("Title");

        lblStart.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblStart.setText("Start");

        lblStop.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblStop.setText("Stop");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("Implementation Time");

        txtFldLfsStpDate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        txtFldLfsStrtDate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtFldLfsStrtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLfsStrtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldLfsStrtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtFldLfsStpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldLfsStpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStop))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStart)
                        .addComponent(txtFldLfsStrtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegLfs.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnRegLfs.setText("Register");
        btnRegLfs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegLfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegLfsActionPerformed(evt);
            }
        });

        btnUpdLfs.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnUpdLfs.setText("Update");
        btnUpdLfs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdLfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdLfsActionPerformed(evt);
            }
        });

        btnClearLfs.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnClearLfs.setText("Clear");
        btnClearLfs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClearLfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearLfsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFldLfsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboLfsType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldLfsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLfsType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearLfs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lstLfsFuture.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLfsFuture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstLfsFutureMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(lstLfsFuture);

        lblMsgLfsFt.setText("Status and Data Analysis");

        jLabel25.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel25.setText(" Future Conditions");

        btnDelLfsFt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnDelLfsFt.setText("Delete");
        btnDelLfsFt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelLfsFt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLfsFtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsgLfsFt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(btnDelLfsFt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelLfsFt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgLfsFt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Future", jPanel9);

        lstLfsIn.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLfsIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstLfsInMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(lstLfsIn);

        lblMsgLfsIn.setText("Status and Data Analysis");

        jLabel27.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel27.setText("In Time Conditions");

        btnDelLfsIn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnDelLfsIn.setText("Delete");
        btnDelLfsIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelLfsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLfsInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMsgLfsIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(btnDelLfsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelLfsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgLfsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("In Time", jPanel10);

        lstLfsExp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLfsExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstLfsExpMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(lstLfsExp);

        lblMsgLfsExp.setText("Status and Data Analysis");

        jLabel29.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel29.setText("Expired Conditions");

        btnDelLfsExp.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnDelLfsExp.setText("Delete");
        btnDelLfsExp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelLfsExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelLfsExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(btnDelLfsExp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMsgLfsExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelLfsExp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(lblMsgLfsExp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jTabbedPane2.addTab("Expired", jPanel11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnViewLfsClear.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnViewLfsClear.setText("Clear");
        btnViewLfsClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewLfsClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLfsClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewLfsClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewLfsClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFldLfsView.setEditable(false);
        txtFldLfsView.setColumns(20);
        txtFldLfsView.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtFldLfsView.setRows(5);
        jScrollPane1.setViewportView(txtFldLfsView);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel4.setText("Viewing Desciption");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setText("      Current Plans");

        lstTrgtFocussed.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstTrgtFocussed);

        txtFldTrgtSearchFocussed.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtFldTrgtSearchFocussed.setText("Target to Search");

        btnTrgtSearchFocussed.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnTrgtSearchFocussed.setText("Search");
        btnTrgtSearchFocussed.setBorder(null);

        lblMsgTrgtFocussed.setText("Status and Count");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMsgTrgtFocussed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addComponent(txtFldTrgtSearchFocussed, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnTrgtSearchFocussed, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFldTrgtSearchFocussed, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnTrgtSearchFocussed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgTrgtFocussed, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Focussed", jPanel13);

        txtFldTrgtSearchExp.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtFldTrgtSearchExp.setText("Target to Search");

        btnTrgtSearchExp.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btnTrgtSearchExp.setText("Search");
        btnTrgtSearchExp.setBorder(null);

        lstTrgtExp.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(lstTrgtExp);

        lblMsgTrgtExp.setText("Status and Count");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10)
                    .addComponent(lblMsgTrgtExp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtFldTrgtSearchExp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnTrgtSearchExp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrgtSearchExp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldTrgtSearchExp, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgTrgtExp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Expired", jPanel12);

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel9.setText("Deadline");

        txtFldTrgtDeadline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFldTrgtDeadline.setText("dd/mm/yy");

        txtFldTrgtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTrgtName.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        lblTrgtName.setText("Target");

        btnTrgtView.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrgtView.setText("View");
        btnTrgtView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTrgtEdit.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrgtEdit.setText("Edit");
        btnTrgtEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTrgtDel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrgtDel.setText("Delete");
        btnTrgtDel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnTrgtView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrgtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTrgtDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFldTrgtName)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldTrgtDeadline)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTrgtName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblTrgtName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldTrgtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldTrgtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrgtView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrgtDel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrgtEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField5.setText("        MENUS");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField5.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuContact.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuContact.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuContact.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuContact.setText("Contact");
        btnMenuContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContactActionPerformed(evt);
            }
        });

        btnMenuPlan.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPlan.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPlan.setText("Plan");
        btnMenuPlan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuPlan.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPlanActionPerformed(evt);
            }
        });

        btnMenuGoals.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuGoals.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuGoals.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuGoals.setText("Goals");
        btnMenuGoals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuGoals.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuGoalsActionPerformed(evt);
            }
        });

        btnMenuProjects.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuProjects.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuProjects.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuProjects.setText("Projects");
        btnMenuProjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuProjects.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProjectsActionPerformed(evt);
            }
        });

        btnMneuTrips.setBackground(new java.awt.Color(0, 0, 0));
        btnMneuTrips.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMneuTrips.setForeground(new java.awt.Color(255, 255, 255));
        btnMneuTrips.setText("Trips");
        btnMneuTrips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMneuTrips.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMneuTrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMneuTripsActionPerformed(evt);
            }
        });

        btnMenuMedias.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuMedias.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuMedias.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuMedias.setText("Medias");
        btnMenuMedias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuMedias.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMediasActionPerformed(evt);
            }
        });

        btnMenuLifeStyle.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuLifeStyle.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLifeStyle.setText("Life Style");
        btnMenuLifeStyle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLifeStyle.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuLifeStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLifeStyleActionPerformed(evt);
            }
        });

        btnMenuLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLogout.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLogout.setText("Logout");
        btnMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLogout.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuSetting.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuSetting.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSetting.setText("Setting");
        btnMenuSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuSetting.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMenuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuProjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnMenuMedias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMneuTrips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMenuContact)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMenuGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMneuTrips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMedias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnMenuSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMenuContact, btnMenuGoals, btnMenuLifeStyle, btnMenuMedias, btnMenuPlan, btnMenuProjects, btnMneuTrips});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldLfsStrtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLfsStrtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLfsStrtDateActionPerformed

    private void btnMenuMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMediasActionPerformed
       this.setVisible(false);
        new medias().setVisible(true);
    }//GEN-LAST:event_btnMenuMediasActionPerformed

    private void btnMenuContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContactActionPerformed
       this.setVisible(false);
        new contacts().setVisible(true);
    }//GEN-LAST:event_btnMenuContactActionPerformed

    private void btnMenuPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPlanActionPerformed
       this.setVisible(false);
        new plan().setVisible(true);
    }//GEN-LAST:event_btnMenuPlanActionPerformed

    private void btnMenuGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuGoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuGoalsActionPerformed

    private void btnMenuProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProjectsActionPerformed
        this.setVisible(false);
        new projects().setVisible(true);
    }//GEN-LAST:event_btnMenuProjectsActionPerformed

    private void btnMneuTripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMneuTripsActionPerformed
       this.setVisible(false);
        new trips().setVisible(true);
    }//GEN-LAST:event_btnMneuTripsActionPerformed

    private void btnMenuLifeStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLifeStyleActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_btnMenuLifeStyleActionPerformed

    private void btnMenuSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSettingActionPerformed
        this.setVisible(false);
        new setting().setVisible(true);
    }//GEN-LAST:event_btnMenuSettingActionPerformed

    private void btnRegLfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegLfsActionPerformed
      try{
        records.addLifeStyle(txtFldLfsTitle.getText(), txtFldLfsDescr.getText(), comboLfsType.getSelectedItem().toString(),txtFldLfsStrtDate.getText(), txtFldLfsStpDate.getText());
        records.futureLifeStyle(lstLfsFuture);
        records.intimeLifeStyle(lstLfsIn);
        records.expiredLifeStyle(lstLfsExp);
        clearLfsForm();
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnRegLfsActionPerformed

    private void lstLfsInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLfsInMouseClicked
        try{
        records.selectedLfsTitle=lstLfsIn.getSelectedValue().toString();
         records.viewLifeStyle(txtFldLfsView);
         records.setFormLfsValues(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'"),
         txtFldLfsTitle, txtFldLfsDescr, comboLfsType, txtFldLfsStrtDate, txtFldLfsStpDate);
 }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_lstLfsInMouseClicked

    private void lstLfsFutureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLfsFutureMouseClicked
        try{
        records.selectedLfsTitle=lstLfsFuture.getSelectedValue().toString();
         records.viewLifeStyle(txtFldLfsView);
         records.setFormLfsValues(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'"),
         txtFldLfsTitle, txtFldLfsDescr, comboLfsType, txtFldLfsStrtDate, txtFldLfsStpDate);
          }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_lstLfsFutureMouseClicked

    private void btnUpdLfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdLfsActionPerformed
     try{
     int lfsid=records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'");
          records.updateLifeStyle(lfsid,
              txtFldLfsTitle.getText(), txtFldLfsDescr.getText(), comboLfsType.getSelectedItem().toString(),txtFldLfsStrtDate.getText(), txtFldLfsStpDate.getText());
      records.futureLifeStyle(lstLfsFuture);
        records.intimeLifeStyle(lstLfsIn);
        records.expiredLifeStyle(lstLfsExp);
      txtFldLfsView.setText("");
      clearLfsForm();
       }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnUpdLfsActionPerformed

    private void btnClearLfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearLfsActionPerformed
        try{
            clearLfsForm();
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnClearLfsActionPerformed

    private void btnViewLfsClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLfsClearActionPerformed
        txtFldLfsView.setText("");
    }//GEN-LAST:event_btnViewLfsClearActionPerformed

    private void btnDelLfsFtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLfsFtActionPerformed

   try{
           records.selectedLfsTitle=lstLfsFuture.getSelectedValue().toString();
       records.deleteLifeStyle(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'"));     
        clearLfsForm();
   }catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Sorry You have to select lifestyle to delete");
   }   
    }//GEN-LAST:event_btnDelLfsFtActionPerformed

    private void btnDelLfsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLfsInActionPerformed
       try{
           records.selectedLfsTitle=lstLfsIn.getSelectedValue().toString();
        records.deleteLifeStyle(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'")); 
           clearLfsForm();
         } catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Sorry You have to select lifestyle to delete");
   }     
    }//GEN-LAST:event_btnDelLfsInActionPerformed

    private void btnDelLfsExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelLfsExpActionPerformed

              try{
           records.selectedLfsTitle=lstLfsExp.getSelectedValue().toString();
        records.deleteLifeStyle(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'")); 
           clearLfsForm();
         } catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Sorry You have to select lifestyle to delete");
   }  
    }//GEN-LAST:event_btnDelLfsExpActionPerformed

    private void lstLfsExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstLfsExpMouseClicked
        try{
        records.selectedLfsTitle=lstLfsExp.getSelectedValue().toString();
         records.viewLifeStyle(txtFldLfsView);
         records.setFormLfsValues(records.returnID("SELECT lfs_id FROM lifestyles WHERE lfs_title='"+records.selectedLfsTitle+"'"),
         txtFldLfsTitle, txtFldLfsDescr, comboLfsType, txtFldLfsStrtDate, txtFldLfsStpDate);
          }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_lstLfsExpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lifestyle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lifestyle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lifestyle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lifestyle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lifestyle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearLfs;
    private javax.swing.JButton btnDelLfsExp;
    private javax.swing.JButton btnDelLfsFt;
    private javax.swing.JButton btnDelLfsIn;
    private javax.swing.JButton btnMenuContact;
    private javax.swing.JButton btnMenuGoals;
    private javax.swing.JButton btnMenuLifeStyle;
    private javax.swing.JButton btnMenuLogout;
    private javax.swing.JButton btnMenuMedias;
    private javax.swing.JButton btnMenuPlan;
    private javax.swing.JButton btnMenuProjects;
    private javax.swing.JButton btnMenuSetting;
    private javax.swing.JButton btnMneuTrips;
    private javax.swing.JButton btnRegLfs;
    private javax.swing.JButton btnTrgtDel;
    private javax.swing.JButton btnTrgtEdit;
    private javax.swing.JButton btnTrgtSearchExp;
    private javax.swing.JButton btnTrgtSearchFocussed;
    private javax.swing.JButton btnTrgtView;
    private javax.swing.JButton btnUpdLfs;
    private javax.swing.JButton btnViewLfsClear;
    private javax.swing.JComboBox comboLfsType;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblDescr;
    private javax.swing.JLabel lblMsgLfsExp;
    private javax.swing.JLabel lblMsgLfsFt;
    private javax.swing.JLabel lblMsgLfsIn;
    private javax.swing.JLabel lblMsgTrgtExp;
    private javax.swing.JLabel lblMsgTrgtFocussed;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStop;
    private javax.swing.JLabel lblTrgtName;
    private javax.swing.JLabel lblType;
    private javax.swing.JList lstLfsExp;
    private javax.swing.JList lstLfsFuture;
    private javax.swing.JList lstLfsIn;
    private javax.swing.JList lstTrgtExp;
    private javax.swing.JList lstTrgtFocussed;
    private javax.swing.JTextArea txtFldLfsDescr;
    private javax.swing.JTextField txtFldLfsStpDate;
    private javax.swing.JTextField txtFldLfsStrtDate;
    private javax.swing.JTextField txtFldLfsTitle;
    private javax.swing.JTextArea txtFldLfsView;
    private javax.swing.JTextField txtFldTrgtDeadline;
    private javax.swing.JTextField txtFldTrgtName;
    private javax.swing.JTextField txtFldTrgtSearchExp;
    private javax.swing.JTextField txtFldTrgtSearchFocussed;
    // End of variables declaration//GEN-END:variables
}
