/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perecords;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
/**
 *
 * @author BPRAdmin
 */
public class medias extends javax.swing.JFrame {
prerecordsmgr records=new prerecordsmgr();
int uid;
    /**
     * Creates new form medias
     */
    public medias() {
        initComponents();
        records.getMedia(tblMedia);
    }
public void cleanMediaForm(){
        txtFldNwName.setText("");
        txtFldUname.setText("");
        txtFldPhone.setText("");
        txtFldEmail.setText("");
        txtFldPwd.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegMedia = new javax.swing.JButton();
        lblPwd = new javax.swing.JLabel();
        txtFldEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtFldPhone = new javax.swing.JTextField();
        txtFldUname = new javax.swing.JTextField();
        lblUname = new javax.swing.JLabel();
        txtFldNwName = new javax.swing.JTextField();
        lblNwName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        txtFldPwd = new javax.swing.JPasswordField();
        btnUpdMedia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSearchMedia = new javax.swing.JButton();
        btnDelMedia = new javax.swing.JButton();
        txtFldSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedia = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        btnMenuContact = new javax.swing.JButton();
        btnMenuPlan = new javax.swing.JButton();
        btnMenuGoals = new javax.swing.JButton();
        btnMenuProjects = new javax.swing.JButton();
        btnMneuTrips = new javax.swing.JButton();
        btnMenuMedias = new javax.swing.JButton();
        btnMenuLifeStyle = new javax.swing.JButton();
        btnMenuLogout = new javax.swing.JButton();
        btnMenuSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONAL RECORDS MANAGEMENT SYSTEM");
        setLocation(new java.awt.Point(12, 30));
        setResizable(false);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jTextField1.setText("                                                         MANAGE MEDIAS INFORMATION");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRegMedia.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnRegMedia.setText("Register");
        btnRegMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegMediaActionPerformed(evt);
            }
        });

        lblPwd.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblPwd.setText("Password");

        txtFldEmail.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblEmail.setText("E-mail");

        lblPhone.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblPhone.setText("Phone");

        txtFldPhone.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        txtFldUname.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        lblUname.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblUname.setText("Username");

        txtFldNwName.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        lblNwName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblNwName.setText("N/W Name");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("                    Register New Media Information");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField8.setText("   Register Unlimited Number of Media Information");

        txtFldPwd.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        btnUpdMedia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdMedia.setText("Update");
        btnUpdMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblNwName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFldNwName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRegMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnUpdMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblUname, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFldUname, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFldPwd))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFldEmail, txtFldNwName, txtFldPhone, txtFldUname});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblNwName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtFldNwName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFldEmail, txtFldNwName, txtFldPhone, txtFldPwd, txtFldUname});

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnSearchMedia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchMedia.setText("SEARCH");
        btnSearchMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSearchMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMediaActionPerformed(evt);
            }
        });

        btnDelMedia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelMedia.setText("Delete");
        btnDelMedia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelMediaActionPerformed(evt);
            }
        });

        txtFldSearch.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NETWORK NAME", "USERNAME", "PHONE", "E-MAIL", "PASSWORD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedia);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField5.setText("        MENUS");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField5.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuContact.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuContact.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuContact.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuContact.setText("Contact");
        btnMenuContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContactActionPerformed(evt);
            }
        });

        btnMenuPlan.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPlan.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPlan.setText("Plan");
        btnMenuPlan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuPlan.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPlanActionPerformed(evt);
            }
        });

        btnMenuGoals.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuGoals.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuGoals.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuGoals.setText("Goals");
        btnMenuGoals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuGoals.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuGoalsActionPerformed(evt);
            }
        });

        btnMenuProjects.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuProjects.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuProjects.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuProjects.setText("Projects");
        btnMenuProjects.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuProjects.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProjectsActionPerformed(evt);
            }
        });

        btnMneuTrips.setBackground(new java.awt.Color(0, 0, 0));
        btnMneuTrips.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMneuTrips.setForeground(new java.awt.Color(255, 255, 255));
        btnMneuTrips.setText("Trips");
        btnMneuTrips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMneuTrips.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMneuTrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMneuTripsActionPerformed(evt);
            }
        });

        btnMenuMedias.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuMedias.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuMedias.setText("Medias");
        btnMenuMedias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuMedias.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMediasActionPerformed(evt);
            }
        });

        btnMenuLifeStyle.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLifeStyle.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLifeStyle.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLifeStyle.setText("Life Style");
        btnMenuLifeStyle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLifeStyle.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuLifeStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLifeStyleActionPerformed(evt);
            }
        });

        btnMenuLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLogout.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLogout.setText("Logout");
        btnMenuLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLogout.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuSetting.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuSetting.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSetting.setText("Setting");
        btnMenuSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuSetting.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMenuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuGoals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuProjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnMenuMedias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMneuTrips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMenuContact)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMenuGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMneuTrips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMedias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLifeStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnMenuSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMenuContact, btnMenuGoals, btnMenuLifeStyle, btnMenuMedias, btnMenuPlan, btnMenuProjects, btnMneuTrips});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMediasActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_btnMenuMediasActionPerformed

    private void btnMenuContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContactActionPerformed
      this.setVisible(false);
        new contacts().setVisible(true);
    }//GEN-LAST:event_btnMenuContactActionPerformed

    private void btnMenuPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPlanActionPerformed
        this.setVisible(false);
        new plan().setVisible(true);
    }//GEN-LAST:event_btnMenuPlanActionPerformed

    private void btnMenuGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuGoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuGoalsActionPerformed

    private void btnMenuProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProjectsActionPerformed
       this.setVisible(false);
        new projects().setVisible(true);
    }//GEN-LAST:event_btnMenuProjectsActionPerformed

    private void btnMneuTripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMneuTripsActionPerformed
      this.setVisible(false);
        new trips().setVisible(true);
    }//GEN-LAST:event_btnMneuTripsActionPerformed

    private void btnMenuLifeStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLifeStyleActionPerformed
       this.setVisible(false);
        new lifestyle().setVisible(true);
    }//GEN-LAST:event_btnMenuLifeStyleActionPerformed

    private void btnMenuSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSettingActionPerformed
        this.setVisible(false);
        new setting().setVisible(true);
    }//GEN-LAST:event_btnMenuSettingActionPerformed

    private void btnRegMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegMediaActionPerformed
        try{
        records.addMedia(txtFldNwName.getText(), txtFldUname.getText(), txtFldPhone.getText(),
                txtFldEmail.getText(), txtFldPwd.getText());
        cleanMediaForm();
        records.getMedia(tblMedia);
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnRegMediaActionPerformed

    private void tblMediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMediaMouseClicked
        try{
        TableModel tmodel=tblMedia.getModel();
        int i=tblMedia.getSelectedRow();
        uid=Integer.parseInt(tmodel.getValueAt(i,0).toString());
        txtFldNwName.setText(tmodel.getValueAt(i,2).toString());
        txtFldUname.setText(tmodel.getValueAt(i,1).toString());
        txtFldPhone.setText(tmodel.getValueAt(i,3).toString());
        txtFldEmail.setText(tmodel.getValueAt(i,4).toString());
        txtFldPwd.setText(records.toStrOrigin(tmodel.getValueAt(i,5).toString()));
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_tblMediaMouseClicked

    private void btnUpdMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdMediaActionPerformed
       try{
        records.updateMedia(uid, txtFldNwName.getText(), txtFldUname.getText(), txtFldPhone.getText(),
               txtFldEmail.getText(), txtFldPwd.getText());
       cleanMediaForm();
       records.getMedia(tblMedia);
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnUpdMediaActionPerformed

    private void btnDelMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelMediaActionPerformed
       try{
        records.deleteMedia(uid);
       cleanMediaForm();
       records.getMedia(tblMedia);
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnDelMediaActionPerformed

    private void btnSearchMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMediaActionPerformed
        try{
        records.searchMedia(tblMedia, txtFldSearch.getText());
         }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry Error Occured "+ex.getMessage());   
       }
    }//GEN-LAST:event_btnSearchMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelMedia;
    private javax.swing.JButton btnMenuContact;
    private javax.swing.JButton btnMenuGoals;
    private javax.swing.JButton btnMenuLifeStyle;
    private javax.swing.JButton btnMenuLogout;
    private javax.swing.JButton btnMenuMedias;
    private javax.swing.JButton btnMenuPlan;
    private javax.swing.JButton btnMenuProjects;
    private javax.swing.JButton btnMenuSetting;
    private javax.swing.JButton btnMneuTrips;
    private javax.swing.JButton btnRegMedia;
    private javax.swing.JButton btnSearchMedia;
    private javax.swing.JButton btnUpdMedia;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNwName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblUname;
    private javax.swing.JTable tblMedia;
    private javax.swing.JTextField txtFldEmail;
    private javax.swing.JTextField txtFldNwName;
    private javax.swing.JTextField txtFldPhone;
    private javax.swing.JPasswordField txtFldPwd;
    private javax.swing.JTextField txtFldSearch;
    private javax.swing.JTextField txtFldUname;
    // End of variables declaration//GEN-END:variables
}
