/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perecords;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author BPRAdmin
 */
public class trips extends javax.swing.JFrame {
prerecordsmgr records=new prerecordsmgr();
    /**
     * Creates new form trips
     */
    public trips() {
        initComponents();
         records.getTrip(lstTrpAll);
          records.getMonthlyTrip(lstTrpMonth);
          records.getWeeklyTrip(lstTrpWk);
          records.doneTrip(lstTrpDone);
          records.failedTrip(lstTrpFail);
    }
    public void clearTripForm(){
    txtFldTrpName.setText("");
     txtFldTrpPurpose.setText("");
     txtFldTrpFrom.setText("");
     txtFldTrpTo.setText("");
     txtFldTrpDate.setText("");
     radSingle.setSelected(true);
     radDouble.setSelected(false);
}
public void clearTripDtForm(){
    txtFldTrpDtName.setText("");
     txtFldTrpDtAmount.setText("");
}
public void removeTrpDt(){
    DefaultTableModel tmodel=(DefaultTableModel) tblTrpDt.getModel();
       tmodel.setRowCount(0);
       tblTrpDt.setModel(tmodel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRegTrp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFldTrpFrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFldTrpPurpose = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFldTrpName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        radSingle = new javax.swing.JRadioButton();
        radDouble = new javax.swing.JRadioButton();
        txtFldTrpDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnUpdTrp = new javax.swing.JButton();
        txtFldTrpTo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrpDt = new javax.swing.JTable();
        btnDelTrpDt = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblMsgTrpAll = new javax.swing.JLabel();
        txtFldTrpSearch = new javax.swing.JTextField();
        btnTrpSearch = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstTrpAll = new javax.swing.JList();
        btnTrpAllEdit = new javax.swing.JButton();
        btnTrpAllDelete = new javax.swing.JButton();
        btnTrpAllDone = new javax.swing.JButton();
        btnTrpAllFailed = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lblMsgTrpWk = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstTrpWk = new javax.swing.JList();
        btnTrpWkEdit = new javax.swing.JButton();
        btnTrpWkDel = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblMsgTrpMonth = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstTrpMonth = new javax.swing.JList();
        btnEditTrpMonth = new javax.swing.JButton();
        btnDelTrpMonth = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTrpDone = new javax.swing.JList();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        txtFldViewTrpDone = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstTrpFail = new javax.swing.JList();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        txtFldViewTrpFail = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaViewTrip = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegTrpDt = new javax.swing.JButton();
        txtFldTrpDtName = new javax.swing.JTextField();
        txtFldTrpDtAmount = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtFldTrpDtTotal = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnUpdTrpDt = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jTextField28 = new javax.swing.JTextField();
        btnMenuContact3 = new javax.swing.JButton();
        btnMenuPlan3 = new javax.swing.JButton();
        btnMenuGoals3 = new javax.swing.JButton();
        btnMenuProjects3 = new javax.swing.JButton();
        btnMneuTrips3 = new javax.swing.JButton();
        btnMenuMedias3 = new javax.swing.JButton();
        btnMenuLifeStyle3 = new javax.swing.JButton();
        btnMenuLogout3 = new javax.swing.JButton();
        btnMenuSetting3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RECORDS MANAGEMENT SYSTEM");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jTextField1.setText("                                                                MANAGE TRIPS");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnRegTrp.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnRegTrp.setText("Register");
        btnRegTrp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegTrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTrpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setText("To");

        txtFldTrpFrom.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setText("Direction");

        txtFldTrpPurpose.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("Purpose");

        txtFldTrpName.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtFldTrpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldTrpNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("Trip Name");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setText("                    Register New Trips Information");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField8.setText("   Register Unlimited Number of Trips");

        buttonGroup1.add(radSingle);
        radSingle.setSelected(true);
        radSingle.setText("Single");

        buttonGroup1.add(radDouble);
        radDouble.setText("Double");

        txtFldTrpDate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("Date");

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel15.setText("      Help Full Information to use this Interface");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpdTrp.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnUpdTrp.setText("Update");
        btnUpdTrp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdTrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdTrpActionPerformed(evt);
            }
        });

        txtFldTrpTo.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtFldTrpFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFldTrpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radSingle, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtFldTrpTo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radDouble)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldTrpPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldTrpName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegTrp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdTrp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtFldTrpName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldTrpPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldTrpFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldTrpTo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldTrpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radSingle)
                    .addComponent(radDouble))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegTrp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdTrp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFldTrpDate, txtFldTrpFrom, txtFldTrpName, txtFldTrpPurpose});

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblTrpDt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TRIP DETAIL NAME", "AMOUNT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrpDt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTrpDt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrpDtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTrpDt);

        btnDelTrpDt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnDelTrpDt.setText("Delete");
        btnDelTrpDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelTrpDtActionPerformed(evt);
            }
        });

        jTextField25.setEditable(false);
        jTextField25.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField25.setText("            Details Saved On Trip");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnDelTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMsgTrpAll.setText("Status Count and Data Analysis");

        txtFldTrpSearch.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        btnTrpSearch.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpSearch.setText("Search");
        btnTrpSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpSearchActionPerformed(evt);
            }
        });

        lstTrpAll.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTrpAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTrpAllMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lstTrpAll);

        btnTrpAllEdit.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpAllEdit.setText("Edit");
        btnTrpAllEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpAllEditActionPerformed(evt);
            }
        });

        btnTrpAllDelete.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpAllDelete.setText("Delete");
        btnTrpAllDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpAllDeleteActionPerformed(evt);
            }
        });

        btnTrpAllDone.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpAllDone.setText("Done");
        btnTrpAllDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpAllDoneActionPerformed(evt);
            }
        });

        btnTrpAllFailed.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpAllFailed.setText("Failed");
        btnTrpAllFailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpAllFailedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lblMsgTrpAll, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnTrpAllDelete))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(btnTrpAllEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnTrpAllDone, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrpAllFailed, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(txtFldTrpSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrpSearch))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrpSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtFldTrpSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrpAllDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTrpAllEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrpAllDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrpAllFailed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgTrpAll, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("All", jPanel6);

        lblMsgTrpWk.setText("Status Count and Data Analysis");

        lstTrpWk.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTrpWk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTrpWkMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(lstTrpWk);

        btnTrpWkEdit.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpWkEdit.setText("Edit");
        btnTrpWkEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpWkEditActionPerformed(evt);
            }
        });

        btnTrpWkDel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnTrpWkDel.setText("Delete");
        btnTrpWkDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrpWkDelActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField2.setText("                      TRIPS IN THIS WEEK");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(lblMsgTrpWk, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnTrpWkDel))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(btnTrpWkEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrpWkDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrpWkEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgTrpWk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("This Week", jPanel7);

        lblMsgTrpMonth.setText("Status Count and Data Analysis");

        lstTrpMonth.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTrpMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTrpMonthMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lstTrpMonth);

        btnEditTrpMonth.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnEditTrpMonth.setText("Edit");
        btnEditTrpMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTrpMonthActionPerformed(evt);
            }
        });

        btnDelTrpMonth.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnDelTrpMonth.setText("Delete");
        btnDelTrpMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelTrpMonthActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField3.setText("                    TRIP IN THIS MONTH");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addContainerGap())
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblMsgTrpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnDelTrpMonth))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnEditTrpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelTrpMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditTrpMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsgTrpMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("This Month", jPanel9);

        lstTrpDone.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstTrpDone);

        jTextField14.setEditable(false);
        jTextField14.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField14.setText("                   Trips Allready Done");

        jTextField15.setEditable(false);
        jTextField15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField15.setText("                                  Analysis");

        txtFldViewTrpDone.setEditable(false);
        txtFldViewTrpDone.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtFldViewTrpDone.setText("    ");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFldViewTrpDone)
                    .addComponent(jTextField14)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldViewTrpDone, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Done", jPanel15);

        lstTrpFail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(lstTrpFail);

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField17.setText("                   Trips Allready Failed");

        jTextField18.setEditable(false);
        jTextField18.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField18.setText("                                  Analysis");

        txtFldViewTrpFail.setEditable(false);
        txtFldViewTrpFail.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        txtFldViewTrpFail.setText("    ");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFldViewTrpFail)
                    .addComponent(jTextField17)
                    .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(5, 5, 5))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldViewTrpFail, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Failed", jPanel16);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField4.setText("            VIEW SELECTED TRIP");

        txtAreaViewTrip.setEditable(false);
        txtAreaViewTrip.setColumns(20);
        txtAreaViewTrip.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtAreaViewTrip.setRows(5);
        jScrollPane3.setViewportView(txtAreaViewTrip);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel8.setText("Details");

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel12.setText("Amount");

        btnRegTrpDt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnRegTrpDt.setText("Add");
        btnRegTrpDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTrpDtActionPerformed(evt);
            }
        });

        txtFldTrpDtName.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        txtFldTrpDtAmount.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel13.setText("Total Amount");

        txtFldTrpDtTotal.setEditable(false);
        txtFldTrpDtTotal.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N

        jTextField23.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField23.setText("RWF");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtFldTrpDtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldTrpDtTotal)
                    .addComponent(jTextField23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField24.setEditable(false);
        jTextField24.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTextField24.setText("            Details On Trip");

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel14.setText("Status Count and Data Analysis");

        btnUpdTrpDt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnUpdTrpDt.setText("Update");
        btnUpdTrpDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdTrpDtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldTrpDtName))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(btnRegTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFldTrpDtAmount)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFldTrpDtName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFldTrpDtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdTrpDt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField28.setEditable(false);
        jTextField28.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jTextField28.setText("        MENUS");
        jTextField28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField28.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuContact3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuContact3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuContact3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuContact3.setText("Contact");
        btnMenuContact3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuContact3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuContact3ActionPerformed(evt);
            }
        });

        btnMenuPlan3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuPlan3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuPlan3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPlan3.setText("Plan");
        btnMenuPlan3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuPlan3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuPlan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPlan3ActionPerformed(evt);
            }
        });

        btnMenuGoals3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuGoals3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuGoals3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuGoals3.setText("Goals");
        btnMenuGoals3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuGoals3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuGoals3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuGoals3ActionPerformed(evt);
            }
        });

        btnMenuProjects3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuProjects3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuProjects3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuProjects3.setText("Projects");
        btnMenuProjects3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuProjects3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuProjects3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProjects3ActionPerformed(evt);
            }
        });

        btnMneuTrips3.setBackground(new java.awt.Color(255, 255, 255));
        btnMneuTrips3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMneuTrips3.setText("Trips");
        btnMneuTrips3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMneuTrips3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMneuTrips3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMneuTrips3ActionPerformed(evt);
            }
        });

        btnMenuMedias3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuMedias3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuMedias3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuMedias3.setText("Medias");
        btnMenuMedias3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuMedias3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuMedias3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMedias3ActionPerformed(evt);
            }
        });

        btnMenuLifeStyle3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLifeStyle3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLifeStyle3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLifeStyle3.setText("Life Style");
        btnMenuLifeStyle3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLifeStyle3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuLifeStyle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLifeStyle3ActionPerformed(evt);
            }
        });

        btnMenuLogout3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuLogout3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuLogout3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLogout3.setText("Logout");
        btnMenuLogout3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuLogout3.setPreferredSize(new java.awt.Dimension(73, 25));

        btnMenuSetting3.setBackground(new java.awt.Color(0, 0, 0));
        btnMenuSetting3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        btnMenuSetting3.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuSetting3.setText("Setting");
        btnMenuSetting3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenuSetting3.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMenuSetting3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSetting3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMenuLogout3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuContact3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuGoals3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPlan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuProjects3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuLifeStyle3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnMenuMedias3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMneuTrips3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuSetting3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMenuContact3)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPlan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMenuGoals3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuProjects3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMneuTrips3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuMedias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuLifeStyle3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnMenuSetting3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMenuLogout3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel25Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMenuContact3, btnMenuGoals3, btnMenuLifeStyle3, btnMenuLogout3, btnMenuMedias3, btnMenuPlan3, btnMenuProjects3, btnMenuSetting3, btnMneuTrips3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldTrpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldTrpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldTrpNameActionPerformed

    private void btnMenuMedias3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMedias3ActionPerformed
        this.setVisible(false);
        new medias().setVisible(true);
    }//GEN-LAST:event_btnMenuMedias3ActionPerformed

    private void btnMenuContact3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuContact3ActionPerformed
        this.setVisible(false);
        new contacts().setVisible(true);
    }//GEN-LAST:event_btnMenuContact3ActionPerformed

    private void btnMenuPlan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPlan3ActionPerformed
       this.setVisible(false);
        new plan().setVisible(true);
    }//GEN-LAST:event_btnMenuPlan3ActionPerformed

    private void btnMenuGoals3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuGoals3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuGoals3ActionPerformed

    private void btnMenuProjects3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProjects3ActionPerformed
        this.setVisible(false);
        new projects().setVisible(true);
    }//GEN-LAST:event_btnMenuProjects3ActionPerformed

    private void btnMneuTrips3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMneuTrips3ActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_btnMneuTrips3ActionPerformed

    private void btnMenuLifeStyle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLifeStyle3ActionPerformed
       this.setVisible(false);
        new lifestyle().setVisible(true);
    }//GEN-LAST:event_btnMenuLifeStyle3ActionPerformed

    private void btnMenuSetting3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSetting3ActionPerformed
        this.setVisible(false);
        new setting().setVisible(true);
    }//GEN-LAST:event_btnMenuSetting3ActionPerformed

    private void btnRegTrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTrpActionPerformed
    try{  String direction="";
      if(radSingle.isSelected()==true){
          direction="single";
      }
      if(radDouble.isSelected()==true){
          direction="double";
      }
        records.addTrip(txtFldTrpName.getText(),txtFldTrpPurpose.getText(), txtFldTrpFrom.getText(), txtFldTrpTo.getText(), txtFldTrpDate.getText(), direction);
        records.getTrip(lstTrpAll);
        records.getMonthlyTrip(lstTrpMonth);
          records.getWeeklyTrip(lstTrpWk);
        clearTripForm();
    }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnRegTrpActionPerformed

    private void btnUpdTrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdTrpActionPerformed
     try{
          String direction="";
      if(radSingle.isSelected()==true){
          direction="single";
      }
      if(radDouble.isSelected()==true){
          direction="double";
      }
      if(records.selectedTripName.length()>0){
        
   int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.updateTrip(trpid, txtFldTrpName.getText(),txtFldTrpPurpose.getText(), txtFldTrpFrom.getText(), txtFldTrpTo.getText(), txtFldTrpDate.getText(), direction);
        records.getTrip(lstTrpAll);
        records.getMonthlyTrip(lstTrpMonth);
          records.getWeeklyTrip(lstTrpWk);
       // records.viewTrip(txtAreaViewTrip);
        clearTripForm();
        clearTripDtForm(); 
        txtAreaViewTrip.setText("");removeTrpDt();
      }else{
          JOptionPane.showMessageDialog(null, "Please you must select Trip to update");
      }
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnUpdTrpActionPerformed

    private void lstTrpAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTrpAllMouseClicked
    try{
        records.selectedTripName=lstTrpAll.getSelectedValue().toString();
      int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.viewTrip(txtAreaViewTrip);
        records.getTripDetail(trpid,tblTrpDt,txtFldTrpDtTotal);
        }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_lstTrpAllMouseClicked

    private void btnRegTrpDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTrpDtActionPerformed
        try{
        records.selectedTripName=lstTrpAll.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
    records.addTripDetail(trpid, txtFldTrpDtName.getText(), txtFldTrpDtAmount.getText());
    records.getTripDetail(trpid, tblTrpDt,txtFldTrpDtTotal);
    clearTripDtForm();clearTripDtForm();
        }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnRegTrpDtActionPerformed

    private void btnDelTrpDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelTrpDtActionPerformed
        try{  
        TableModel tmodel=tblTrpDt.getModel();
        int tblRow=tblTrpDt.getSelectedRow();
        records.selectedTripName=lstTrpAll.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
       trpdtid=Integer.parseInt(tmodel.getValueAt(tblRow,0).toString());
       records.deleteTripDetail(trpdtid,"detail");
       records.getTripDetail(trpid, tblTrpDt, txtFldTrpDtTotal);
       }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnDelTrpDtActionPerformed
int trpdtid;
    private void btnUpdTrpDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdTrpDtActionPerformed
       try{
        records.selectedTripName=lstTrpAll.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.updateTripDetail(trpdtid, txtFldTrpDtName.getText(),  txtFldTrpDtAmount.getText());
        records.getTripDetail(trpid, tblTrpDt, txtFldTrpDtTotal);
        clearTripDtForm();
        }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnUpdTrpDtActionPerformed

    private void tblTrpDtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrpDtMouseClicked
     try{
        TableModel tmodel=tblTrpDt.getModel();
        int tblRow=tblTrpDt.getSelectedRow();
       trpdtid=Integer.parseInt(tmodel.getValueAt(tblRow,0).toString());
        txtFldTrpDtName.setText(tmodel.getValueAt(tblRow,1).toString());
        txtFldTrpDtAmount.setText(tmodel.getValueAt(tblRow,2).toString());
}catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_tblTrpDtMouseClicked

    private void btnTrpSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpSearchActionPerformed
       try{
        if(txtFldTrpSearch.getText().equals("") || txtFldTrpSearch.getText().equals("1") || txtFldTrpSearch.getText().equals("*") || txtFldTrpSearch.getText().equals("all")){
        records.searchTrip(lstTrpAll,"1");
           }else{
    records.searchTrip(lstTrpAll,"trp_name LIKE '"+txtFldTrpSearch.getText()+"%' OR trp_from LIKE '"+txtFldTrpSearch.getText()+"%' OR trp_to LIKE '"+txtFldTrpSearch.getText()+"%'");
        }
           clearTripForm();
          this.removeTrpDt();
           txtAreaViewTrip.setText("");
           }catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_btnTrpSearchActionPerformed

    private void btnTrpAllDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpAllDeleteActionPerformed
              try{
                  records.selectedTripName=lstTrpAll.getSelectedValue().toString();
              
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
       records.deleteTripDetail(trpid,"trip");
       records.deleteTrip(trpid);
       records.getTrip(lstTrpAll);
       }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry you have to select trip to delete");   
       }
    }//GEN-LAST:event_btnTrpAllDeleteActionPerformed

    private void btnTrpAllEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpAllEditActionPerformed
        try{
            records.selectedTripName=lstTrpAll.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.setFormTripValues(trpid, txtFldTrpName, txtFldTrpPurpose, txtFldTrpFrom, txtFldTrpTo, txtFldTrpDate);
        if(records.radioValues.equals("single")){
            radSingle.setSelected(true);
        }else{
            radDouble.setSelected(true);
        }
    } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Sorry you have to select trip to Edit");
                }
    }//GEN-LAST:event_btnTrpAllEditActionPerformed

    private void btnTrpAllDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpAllDoneActionPerformed
        try{
            records.selectedTripName=lstTrpAll.getSelectedValue().toString();
            int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
            records.updateTripStatus(trpid,"done");
                records.getTrip(lstTrpAll);
          records.doneTrip(lstTrpDone);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select Trip to update");
        }
    }//GEN-LAST:event_btnTrpAllDoneActionPerformed

    private void btnTrpAllFailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpAllFailedActionPerformed
         try{
            records.selectedTripName=lstTrpAll.getSelectedValue().toString();
            int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
            records.updateTripStatus(trpid,"fail");
            records.getTrip(lstTrpAll);
            records.failedTrip(lstTrpFail);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select Trip to update");
        }
    }//GEN-LAST:event_btnTrpAllFailedActionPerformed

    private void lstTrpWkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTrpWkMouseClicked
       try{
        records.selectedTripName=lstTrpWk.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.viewTrip(txtAreaViewTrip);
        records.getTripDetail(trpid,tblTrpDt,txtFldTrpDtTotal);
}catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_lstTrpWkMouseClicked

    private void lstTrpMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTrpMonthMouseClicked
try{        
        records.selectedTripName=lstTrpMonth.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.viewTrip(txtAreaViewTrip);
        records.getTripDetail(trpid,tblTrpDt,txtFldTrpDtTotal);
}catch(Exception ex){
          JOptionPane.showMessageDialog(null, "Sorry Error Occured "+ex.getMessage());
      }
    }//GEN-LAST:event_lstTrpMonthMouseClicked

    private void btnTrpWkEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpWkEditActionPerformed
       try{
            records.selectedTripName=lstTrpWk.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.setFormTripValues(trpid, txtFldTrpName, txtFldTrpPurpose, txtFldTrpFrom, txtFldTrpTo, txtFldTrpDate);
        if(records.radioValues.equals("single")){
            radSingle.setSelected(true);
        }else{
            radDouble.setSelected(true);
        }
    } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Sorry you have to select trip to Edit");
                }
    }//GEN-LAST:event_btnTrpWkEditActionPerformed

    private void btnTrpWkDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrpWkDelActionPerformed
         try{
                  records.selectedTripName=lstTrpWk.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
       records.deleteTripDetail(trpid,"trip");
       records.deleteTrip(trpid);
       records.getWeeklyTrip(lstTrpWk);
       }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry you have to select trip to delete");   
       }
    }//GEN-LAST:event_btnTrpWkDelActionPerformed

    private void btnEditTrpMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTrpMonthActionPerformed
        try{
            records.selectedTripName=lstTrpMonth.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
        records.setFormTripValues(trpid, txtFldTrpName, txtFldTrpPurpose, txtFldTrpFrom, txtFldTrpTo, txtFldTrpDate);
        if(records.radioValues.equals("single")){
            radSingle.setSelected(true);
        }else{
            radDouble.setSelected(true);
        }
    } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Sorry you have to select trip to Edit");
                }
    }//GEN-LAST:event_btnEditTrpMonthActionPerformed

    private void btnDelTrpMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelTrpMonthActionPerformed
        try{
     records.selectedTripName=lstTrpMonth.getSelectedValue().toString();
       int trpid=records.returnID("SELECT * FROM trip WHERE trp_name='"+records.selectedTripName+"'");
      records.deleteTripDetail(trpid,"trip");
       records.deleteTrip(trpid);
       records.getMonthlyTrip(lstTrpMonth);
       }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Sorry you have to select trip to delete");   
       }
    }//GEN-LAST:event_btnDelTrpMonthActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelTrpDt;
    private javax.swing.JButton btnDelTrpMonth;
    private javax.swing.JButton btnEditTrpMonth;
    private javax.swing.JButton btnMenuContact3;
    private javax.swing.JButton btnMenuGoals3;
    private javax.swing.JButton btnMenuLifeStyle3;
    private javax.swing.JButton btnMenuLogout3;
    private javax.swing.JButton btnMenuMedias3;
    private javax.swing.JButton btnMenuPlan3;
    private javax.swing.JButton btnMenuProjects3;
    private javax.swing.JButton btnMenuSetting3;
    private javax.swing.JButton btnMneuTrips3;
    private javax.swing.JButton btnRegTrp;
    private javax.swing.JButton btnRegTrpDt;
    private javax.swing.JButton btnTrpAllDelete;
    private javax.swing.JButton btnTrpAllDone;
    private javax.swing.JButton btnTrpAllEdit;
    private javax.swing.JButton btnTrpAllFailed;
    private javax.swing.JButton btnTrpSearch;
    private javax.swing.JButton btnTrpWkDel;
    private javax.swing.JButton btnTrpWkEdit;
    private javax.swing.JButton btnUpdTrp;
    private javax.swing.JButton btnUpdTrpDt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblMsgTrpAll;
    private javax.swing.JLabel lblMsgTrpMonth;
    private javax.swing.JLabel lblMsgTrpWk;
    private javax.swing.JList lstTrpAll;
    private javax.swing.JList lstTrpDone;
    private javax.swing.JList lstTrpFail;
    private javax.swing.JList lstTrpMonth;
    private javax.swing.JList lstTrpWk;
    private javax.swing.JRadioButton radDouble;
    private javax.swing.JRadioButton radSingle;
    private javax.swing.JTable tblTrpDt;
    private javax.swing.JTextArea txtAreaViewTrip;
    private javax.swing.JTextField txtFldTrpDate;
    private javax.swing.JTextField txtFldTrpDtAmount;
    private javax.swing.JTextField txtFldTrpDtName;
    private javax.swing.JTextField txtFldTrpDtTotal;
    private javax.swing.JTextField txtFldTrpFrom;
    private javax.swing.JTextField txtFldTrpName;
    private javax.swing.JTextField txtFldTrpPurpose;
    private javax.swing.JTextField txtFldTrpSearch;
    private javax.swing.JTextField txtFldTrpTo;
    private javax.swing.JTextField txtFldViewTrpDone;
    private javax.swing.JTextField txtFldViewTrpFail;
    // End of variables declaration//GEN-END:variables
}
